### ISSUE TITLE
Different OS testing

### ISSUE THREAD

**Issue by MurakamiTestudo** [SKKU-ESLAB/selective-connection#32]
The framework is tested on specific hardware (Raspberry Pi 3, Pixel 1) and OS versions (Raspbian Jessie 2016.11, Android 7.1). Users with different hardware or newer OS versions might encounter compatibility issues. It would be helpful to have a list of compatible devices and OS versions or information on how to adapt the framework for other environments

**Comment by Podossiu** [comment]
Please leave accurate information regarding the compatibility issue.
